services:
  - type: web
    name: nora-nexora
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python nora_bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
